ALL_BELOW_21_1 = ['railway-signal-communication-ltd', 'china-national-nuclear-power-co-ltd', 'zijin-mining',
                  'nari-tech', 'huaneng-lancang-river-a', 'jinfeng-invest', 'southern-air', 'hedy-holding-a',
                  'new-hope-liuhe-a', 'orient-securities-co-ltd', 'sh-electric-ss', 'china-molybden',
                  'bank-of-jiangsu-co-ltd', 'china-east-air-ss', 'great-wall-mot', 'cn-power-const', 'baotou-steel',
                  'rongsheng-a', 'cn-coal-energy', 'huajing', 'bank-of-nanjin', 'aluminium-corp', 'china-oilfield-ss',
                  'tongwei', 'metallurgical', 'hongta-securities-co-ltd', 'china-cosco', 'sinotex-invest', 'lujiazui',
                  'chinese-town-a', 'xj-goldwind-a', 'jpmf-guangdong-a', 'founder-securi', 'zheneng-elec-p',
                  'zhejiang-century-huatong', 'shanghai-pharm', 'yanzhou-coal', 'gemdale', 'ningbo-port',
                  'datang-power', 'jiangsu-exp', 'jiangxi-copper-ss', 'everbright', 'dahua-tech-a',
                  'merchant-express-a', 'china-great-wall', 'gd-power', 'avic-aircraft-a', 'longsheng',
                  'jiangxi-zhengbang-technology-co-ltd']
ALL_BELOW_21_2 = ['cgn-power', 'boe-technology-a', 'east-money-information', 'great-wall-com-a', 'agri-bank-of-c',
                  'jpmf-guangdong-a', 'cn-shipbuildin', 'icbc-ss', 'shuang-ta-food-a', 'baotou-steel', 'eagle-mining',
                  'zijin-mining', 'dakang-farming-a', 'wintime-energy', 'tcl-corp-a', 'hongta-securities-co-ltd',
                  'ping-an-bank-a', 'green-hitech-a', 'huakong-seg-a', 'hyron-software-a', 'red-arrow-a',
                  'hedy-holding-a', 'longsheng', 'lifan-industry', 'shenzhen-h-t-a', 'js-kingfield-a',
                  'wuhu-token-sciences', 'zheguangsha', 'xcmg-machinery-a', 'jiangxi-zhengbang-technology-co-ltd',
                  'beijing-vrv-software-corp-ltd', 'chunxing-pre-mec-a', 'aerospace-elec', 'n.-china-pharm',
                  'shenzhen-kaifa-a', 'o-film-tech-a', 'huatian-tech-a', 'dabeinong-tech-a', 'united-network',
                  'goertek-a', 'freetrade-tech', 'haitong-sec-ss', 'hebang-corp', 'cssc-steel', 'shenzhen-seg-a',
                  'first-capital-securities-a', 'huachang-chem-a', 'zhenjiang-dongfang-electric-heat', 'heungkong-hold',
                  'cs-zoomlion-a']
ALL_BELOW_21_3 = ['navinfo-a', 'anhui-shengyun-environment-protect', 's-goldleaf-jewel-a', 'huatai-securit',
                  's-beiya-ind', 'anxin-trust', 'sealand-securiti-a', 'petrochina-ss', 'sz-ch-bicycle-a',
                  'changjiang-ele', 'beijing-jetsen-tech-co', 'jilong-gold', 'bank-of-comm', 'luxin-packing-a',
                  'huaneng-lancang-river-a', 'shaanxi-trust-a', 'sanan-optoelec', 'gezhouba', 'sichuan-gaojin-a',
                  'realcan-pharm-a', 'twin-tower-a', 'zh-semicon-a', 'sz-capstone-a', 'shenzhen-sdg-information-co-ltd',
                  'foxconn', 'suning-commerce-a', 'aerospace-comm', 'pangda-automob', 'weichai-power-a',
                  'citic-heavy-in', 'shandong-iron', 'jiangsu-hoperun-software', 'industrial-sec', 'raas-blood-a',
                  'kangqiang-elect-a', 'china-harzone-industry', 'shanghai-const', 'railway-signal-communication-ltd',
                  'metallurgical', 'start-group', 'ningbo-tech-a', 'china-publishing-media', 'tontec-tech',
                  'guangdong-bobaolon-co-ltd', 'changlin', 'linzhou-mach-a', 'zhongnan-cons-a', 'bank-of-suzhou',
                  'sunbird-yacht', 'hongxing-steel']
ALL_BELOW_21_4 = ['guangdong-huasheng-electrical-a', 'chongqing-lummy-pharmaceutical', 'beijing-bank', 'zhongjin-gold',
                  'jihua-group', 'changchun-dep', 'zhongtian-tech', 'join-cheer-soft-a', 'dahua-tech-a',
                  'huahai-pharma', 'tongyu-heavy-industry', 'taigang-a', 'jingxin-pharm-a', 'jinjian-cereal', 'yinge',
                  'china-great-wall', 'shunrong-auto-a', 'victoryprecision-a', 'jiangxi-huawu-brake', 'jingui-silver-a',
                  'tongwei', 'guangzhou-ship', 'cpt-tech-group-a', 'lecron-energy-saving-materials',
                  'holitech-technology-co-ltd', 'shenghua-biok', 'gold-seed-wine', 'dunhuang-seed', 'gf-securities-a',
                  'baoan-real-estate-a', 'dhc-software-a', 'huayi-brothers-media-corp', 'beijing-enlight-media',
                  'beifang-chuang', 'shenzhen-riland-industry-co', 'rare-earth', 'sunwoda-electronic',
                  'caitong-securities', 'baiyin-nonferrous-group-co-ltd', 'guangtai-equip-a', 'sungrow-power-supply',
                  'rongtai', 'bohai-leasing-a', 'meidu', 'xuzhou-wuyang-technology', 'ningbo-huaxiang-a',
                  'shanghai-kingstar-winning-software', 'sh-belling', 'chengdu-santai-holding-group-co-ltd',
                  'cn-coal-energy']
ALL_BELOW_21_5 = ['jiangsu-sanyou-group-co-ltd', 'hainan-airline', 'xinjiang-machinery-research-inst',
                  'zhejiang-dehong-automotive-electric', 'zhongzhu-holdi', 'nanjing-securities-co', 'western-mining-co',
                  'air-china-ss', 'gd-power', 'haige-communicat-a', 'shenzhen-sunwin-intelligent',
                  'shenwan-hongyuan-group-co-ltd', 'anhui-shenjian-new-materials-co-ltd', 'sunnada-comm-a',
                  'yonghui-stores', 'ming-yang-smart-energy-group', 'softto-a', 'jiangsu-nata-opto-electr-material',
                  'xinchao-indust', 'china-galaxy-securities-co-ltd', 'huaxi-securities-a', 'ht-opticelectr',
                  'aluminium-corp', 'greattown', 'jiangsu-dagang-a', 'north-navigati', 'jinhua-chemical-a',
                  'zhejiang-runtu-a', 'shanxi-zhendong-pharmaceutical', 'huadian-power', 'aerospace-h-tech-a',
                  'xinan-chemical', 'wuhan-ps-information-tech', 'citic-guoan-a', 'kaile', 'yuguang',
                  'humon-smelting-a', 'dongguan-kingsun-optoelectron-a', 'zhiguang-elec-a', 'hongdu-avia',
                  'jinling-mining-a', 'soochow-securi', 'yunnan-tin-a', 'cn-railway-grp', 'bank-of-nanjin',
                  'huadong-tech-a', 'pci-suntek-tec', 'guangshen-rail-ss', 'chenzhou-mining-a', 'yunnan-alumin-a']
ALL_BELOW_21_6 = ['foton-motor', 'renhe-pharm-a', 'zhongchangmari', 'sailun', 'southern-air', 'shenzhen-mys-a',
                  'beijing-shouhang-resou-saving-a', 'broad-ocean-a', 'risen-energy', 'sz-coship-elect-a',
                  'xj-goldwind-a', 'chengxing-chem', 'avic-heavy', 'anhui-great-wall-military-industry',
                  'shenzhen-everwin-precision-tech', 'daqin-railway', 'guizhou-tyre-a', 'haite-high-tech-a',
                  'netposa-technologies-ltd', 'liaoning-hongyang', 'zixin-pharm-a', 'net263-a', 'taier-heavy-ind-a',
                  'yango-a', 'sz-sunlord-elec-a', 'gosuncn-a', 'xibei-bearing-a', 'beijing-etrol-tech', 'qingdao-haier',
                  'zz-mining-mach', 'gcl-system-integration-technology', 'western-region-gold-co-ltd',
                  'hand-enterprise-solutions-co', 'shaanxi-jr-fire-protection', 'csr-corp', 'shandong-mining-a',
                  'sw-securities', 'goworld-a', 'zhejiang-sanhua-co-ltd', 'kingenta-eco-a',
                  'guotai-junan-securities-co-ltd', 'yanjing-brewery-a', 'shaanxi-coal', 'sh-intl-port', 'conba',
                  'dali-technology-a', 'hebei-steel-a', 'pgvt-a', 'zhejiang-jinke-peroxides-co-ltd', 'fengle-seed-a']
ALL_BELOW_21_7 = ['titan-wind-energy-suzhou', 'taiji-indust', 'new-century-a', 'guanlu-a', 'shaanxi-heimao',
                  'cn-first-heavy', 'huaren-pharma', 'hongda-xingye-a', 'aerospace-auto', 'kingteller-tech-a',
                  'sh-jiabao', 'keybridge-com-a', 'bluedon-info-security-tech', 'bbmg-corp', 'shenzhen-mtc-a',
                  'huaxin-cement', 'chinese-town-a', 'china-east-air-ss', 'shengda-mining-a', 'shenzhen-infogem',
                  'yangtze-power', 'shenzhen-liantronics', 'lanzhou-ls-heavy-equipment-co', 'wonders-information',
                  'tianyuan-tech-a', 'jiangsu-jin-tong-ling-fluid-mach', 'huafang', 'changhong-elec',
                  'fujian-superpipe', 'jiangsu-dewei-materials', 'yili-energy', 'donghua', 'das-intellitech-a',
                  'microelect', 'huajing', 'beijing-philisense-tech', 'sz-airport-a', 'shenzhen-refond-optoelectronics',
                  'avit', 'science-city-a', 'suzhou-tianma-specialty-chem', 'strong-year', 'fangda', 'yn-germanium-a',
                  's-tianjin-mari', 'lens-technology-co-ltd', 'hangzhou-century', 'tengda-constr', 'hisoar-pharm-a',
                  'sumavision-technologies']

ALL_BELOW_21_8 = ['erfangji', 'zhongjin-a', 'anshan-senyuan-road-bridge', 'new-sea-union-a', 'techo-telecom-a',
                  'konka-a', 'taiya-shoes-co-ltd', 'crystal-optech-a', 'harbin-hi-tech', 'jinfeng-invest', 'surekam-a',
                  'zhengtong-elec-a', 'baoshan-steel', 'fenghuo-elec-a', 'harbin-hatou', 'beijing-sinnet-tech',
                  'ningbo-yak-tech-a', 'victor-on-text-a', 'valin-steel-a', 'akcome-solar-a', 'heihua', 'ronghua-ind',
                  'nanjing-panda', 'xiamen-anne-corp-ltd', 'ygsoft-a', 'shenzhen-dvision-video-communica', 'ourpalm',
                  'chengdu-techcent-environment', 'sz-topband-a', 'ningbo-port', 'china-shipping',
                  'yantai-zhenghai-magnetic-mat', 'beijing-jiaxun-feihong-electrical', 'jian-feng-chem-a',
                  'kunming-longjin-pharma', 'py-refractories-a', 'meihua-holding', 'brilliance-tech', 'xinhu-zhongbao',
                  'zheneng-elec-p', 'sinosun-tech', 'eternal-asia-a', 'b-soft-co-ltd', 'guangdong-hongda-blasting-a',
                  'aero-engine-ctrl-a', 'swan-fiber-co-ltd', 'yin-he-elec-a', 'hongtu-hi-tech',
                  'shanxi-baiyuan-trousers-chain-a', 'cnnc-hua-yuan-a']

ALL_BELOW_21_9 = ['feilo-acoustic', 'yunsheng', 'huilong-agri-pro-a', 'grinm-material', 'pudong-dev', 'northeast-sec-a',
                  'citic-helicop-a', 'rongxin-power-electronic-co-ltd', 'zhejiang-huatie-construction-safety',
                  'tellhow', 'sichuan-troy-information-tech', 'orient-securities-co-ltd', 'eastcompeace-a',
                  'zhongtian-urban-a', 'junzheng-ene-c', 'kyland-tech', 'danfu-compressor-a', 'yatai-pharm-a',
                  'surfilter-network-tech', 'xishan-coal-a', 'fj-nanping-sun-a', 'aerosun-corp',
                  'elefirst-science-tech', 'zhonghang-electronic-measuring-inst', 'guangdong-hongteo-accurate-tech',
                  'nanfang-pump-industry', 'yangquan-coal', 'fujian-snowman-a', 'org-packaging-a', 'susino-umbrella-a',
                  'gold-jade', 'changyuan', 'v-v-food---bev', 'ba-yi-steel', 'luxi-a',
                  'shenzhen-yitoa-intelligent-control', 'golden-horse-a', 'advanced-a', 'linewell-software-co-ltd',
                  'tianma-microelec-a', 'beijing-baofeng-technology', 'shenyang-mach-a', 'souyute-fashion-a',
                  'tatwah-smartech-co-ltd', 'zhenhua-tech-a', 'dongfang-elec-ss', 'hi-target-navigation-tech-co',
                  'guoguang-elec-a', 'shenwu-environmental-tech', 'yq-sea-cucumber-a']
ALL_BELOW_21_10 = ['shanghai-kinetic-medical-co', 'chinalin-securities', 'sinotrans-a', 'chengfa-tech',
                   'cn-avic-avioni', 'hengkang-medical-a', 'hangzhou-shunwang-tech', 'insigma', 'tiancheng',
                   'wuhu-port', 'dayuan-chem', 'china-cosco', 'boyun-new-mat-a', 'joincare', 'huaan-securities-co-ltd',
                   'beijing-cisri-gaona-materials-tech', 'china-ship', 'gemdale', 'selen-sci-tech-a', 'tongfang',
                   'changjiang-sec-a', 'sz-woer-a', 'bi-of-oriental-nations', 'aerospace-cf',
                   'nantong-metalforming-equipment', 'yankon-group', 'china-shenhua', 'zhejiang-kan-a',
                   'kaiser-china-holding-co-ltd', 'huaying-agri-a', 'nanjing-steel', 'chengdu-xiling-power-a',
                   'xingfa-chem', 'roshow-technology-co-ltd', 'tianshan-wool-a', 'hisun-pharm',
                   'centre-testing-intl-shenzhen', 'guofeng-plast-a', 'nationz-technologies-inc', 'cn-chemical',
                   'hunan-er-kang-pharmaceutical', 'juli-sling-a', 'tangshan-port', 'hengshun-vineg',
                   'jinjia-printing-a', 'huachangda-intelligent', 'tianguang-fire-fighting-co-ltd',
                   'shenzhen-sunline-tech', 'talkweb-info-sys-a', 'everbright']
WINE_BELOW_21 = ['yanjing-brewery-a', 'yantai-changyu-pioneer-wine', 'anhui-yingjia-distillery-co-ltd',
                 'zhujiang-brewery-a', 'hs-laobaigan', 'shanghai-bairun-a', 'yilite', 'guyuelongshan',
                 'jinhui-liquor-co-ltd', 'qinghai-huzhu-barley-wine-a', 'gold-seed-wine', 'kuaijishan',
                 'wei-long-grape-wine-co-ltd', 'jinfeng-wine', 'citic-guoan-vi', 'gansu-mogao', 'tonghua-wine',
                 'huiquan-brew', 'lan-huanghe-a', 'tibet-galaxy-a']
SEMI_BELOW_21 = ['huatian-tech-a', 'circuit-tech-a', 'silan-microele', 'changjiang-ele', 'sanan-optoelec',
                 'zh-semicon-a', 'kangqiang-elect-a', 'sunbird-yacht', 'sh-belling', 'wuhan-ps-information-tech',
                 'risen-energy', 'gcl-system-integration-technology', 'goworld-a', 'taiji-indust', 'aerospace-auto',
                 'microelect', 'hangzhou-century', 'akcome-solar-a', 'grinm-material', 'tellhow',
                 'tatwah-smartech-co-ltd', 'nationz-technologies-inc', 'datang-telecom', 'bomin-electronics-co-ltd',
                 'zhuhai-orbita-control-eng', 'topraysolar-a', 'nt-microelectron-a', 'suzhou-good-ark-a',
                 'shenzhen-mason-technologies-a', 'chaohua-tech-a', 'shenzhen-jufei-optoelectronics',
                 'shenzhen-suntak-circuit', 'shenzhen-changfang-light-emitting', 'victory-giant-technology-huizhou-co',
                 'olympic-circuit-technology-co-ltd', 'hubei-dinglong-chemical', 'yangzhou-yangjie-electronic',
                 'zhejiang-xinneng-photovoltaic-tech', 'zongyi', 'ellington-elec', 'wuhan-tianyu-info-industry',
                 'jiangsu-jiejie-microelectronics', 'focus-lightings-tech', 'lianchuang',
                 'jiangsu-huasheng-tianlong-photo', 'jingyuntong-te', 'nationstar-a', 'dongguang-micro-a',
                 'zhejiang-sunflower-light-energy', 'mls-co-ltd']
ALL_BELOW_21_11 = ['dikang-pharm', 'sinoma-science-a', 'zongshen-power-a', 'jiangsu-changshu-rural-commercial-b',
                   'datang-telecom', 'sh-dazhong', 'tj-tianbao-a', 'jiangxi-sanchuan-water-meter', 'shanying-paper',
                   'bomin-electronics-co-ltd', 'shangfeng-cement-a', 'sgis-a', 'tianan-coal', 'misho-ecology-landscape',
                   'hainan-zhenghe', 'beijing-ultrapower-software', 'focused-photonics-hangzhou-inc', 'tecon-animal-a',
                   'xingyuan-environment-tech', 'guangdong-eastone-century', 'qilianshan', 'neusoft-corp',
                   'faw-xiali-a', 'guangzheng-steel-a', 'luan-env-ener', 'beijing-jingxi-culture-a',
                   'jiangsu-welle-environmental', 'ctv-media', 'hs-laobaigan', 'kingsignal-tech',
                   'leyard-optoelectronic', 'shenzhen-terca-a', 'dalian-rubber', 'brother-enterpri-a', 'fudan-forward',
                   'eastern-investment-a', 'chengdu-corpro-technology-co-ltd', 'merchants-ship', 'guanfu-co-ltd-a',
                   'shenzhen-gongjin-electronics', 'ccoop-group', 'senyuan-electric-a', 'shenglu-telecom-a',
                   'zhongken-agri', 'cts-logistics', 'hytera-communica-a', 'faw-car-a', 'zhuhai-orbita-control-eng',
                   'invengo-a', 'huifeng-agrochem-a']
ALL_BELOW_21_12 = ['southwest-phar', 'jiangsu-zijin-rural-commercial-bank', 'shen-huo-a', 'gd-advertising-a',
                   'changshu-tianyin-electromechan', 'broadcast---tv', 'new-wellful', 'orient-group',
                   'grg-banking-equipment-co-ltd',
                   'china-baoan-group-co-ltd', 'topraysolar-a', 'huaye', 'jiangsu-shagang-a', 'eastern-comms',
                   'dr.-peng',
                   'jidong-cement-a', 'huizhou-speed-wireless', 'jinxinnong-feed-a', 'risesun-real-est-a',
                   'kunming-pharm', 'baoshuo',
                   'dalian-daxian', 'norinco-a', 'dongguan-eontec', 'shenzhen-ysstech-info-tech',
                   'shenzhen-huapengfei-logistics',
                   'xinyu-iron', 'harbin-gloria-pharmaceuticals', 'zheshang-securities',
                   'dalian-huarui-heavy-industry-a',
                   'meiyan-jixiang', 'yunnan-xiyi-ind-a', 'beijing-andawell-a', 'huaneng-power', 'wuhan-fingu-a',
                   'chongqing-stee',
                   'central-china-securities-co-ltd', 'shenzhen-fenda-technology-a', 'liuguo-chem', 'soyea-a',
                   'bank-of-shanghai-co-ltd',
                   'binjiang-re-a', 'tibet-summit', 'mengdian', 'shanghai-pharm', 'int-industry-a', 'yantai-tayho-a',
                   'aerospace-pwr',
                   'founder-securi', 'china-national-nuclear-power-co-ltd']
ALL_BELOW_21_13 = ['rastar-group', 'tdg-holding', 'sinovel-wind-g', 'tongling-jingd', 'denghai-seeds-a', 'capital-dev',
                   'dongfang-precisn-a', 'cn-metal-eng-a', 'tronly-new-electron-materials', 'baichuan-chem-a',
                   'sino-platinum',
                   'lanhua-sci-tec', 'zhejiang-firstar-panel-tech', 'sinotex-invest', 'yunnan-copper-a',
                   'hualing-xingma',
                   'janus-dongguan-precision', 'beijing-sojo-electric-co-ltd', 'zhongsheng-pharm-a',
                   'shenzhen-tianyuan-dic-info-tech',
                   'wuzhou-comm', 'dmegc-magnetics-a', 'bj-capital', 'henan-kedi-dairy-industry-co-ltd',
                   'cn-commu-cons', 'dongbao-pharm',
                   'zhongda-group', 'xuzhou-combustion-control-tech', 'gi-technologies-beijing',
                   'duzhe-publishing---media-co-ltd',
                   'sinolink-sec', 'tianshan-cemen-a', 'changshu-ruite-electric', 'cyts-tours', 'guanghui-energ',
                   'maanshan-iron-ss',
                   'jinling', 'wanxiang-donee', 'china-oilfield-ss', 'jianglong-shipbuilding', 'jinyu-group',
                   'hz-hangyang-a', 'haibo',
                   'greatoo-a', 'hualu-hs-chem', 'nt-microelectron-a', 'tiandi-tech', 'shenzhen-xinguodu-tech',
                   'suzhou-jinfu-new-material-co', 'suzhou-good-ark-a']
ALL_BELOW_21_14 = ['shenzhen-mason-technologies-a', 'hongda-mining', 'tangel-publishing', 'zhejiang-med',
                   'suplet-power', 'dongxing-securities', 'veken-elite', 'sz-textile-a', 'ganfeng-lithium-a',
                   'xinmin-textile-a', 'cn-citic-bank', 'xinmao-sci-tech-a', 'guosen-securities-co-ltd', 'gem-year-ind',
                   'yuanxing-energy-a', 'bank-of-jiangsu-co-ltd', 'qiming-info-tech-a', 'gpro-titanium-a',
                   'gohigh-data-a', 'neptunus-bioen-a', 'sh-electric-ss', 'shanxi-coal', 'jinduicheng',
                   'orient-landscape-a', 'maling', 'zj-dilong-a', 'unilumin', 'canny-elevator-a',
                   'western-securities-a', 'china-merchant', 'tang-sanyou', 'beijing-miteno-communication',
                   'qingdao-rural', 'china-tianying-inc', 'beyondsoft-a', 'beijing-chinese-digital-publis',
                   'tianjin-pengling-rubber-hose', 'shenzhen-jiawei-lighting', 'huaxicun-a', 's-yizheng-chem',
                   'nanjing-dept', 'sz-zero-seven-a', 'shenzhen-tatfook-tech', 'changan-auto-a',
                   'lander-real-estate-co-ltd', 'jiangxi-cement-a', 'boomsense-tech', 'sichuan-road', 'jiuzhitang-a',
                   'hubei-biocause-pharmaceutical']
ALL_BELOW_21_15 = ['yifan-xinfu-a', 'cashway-tech', 'huajin-chemical-a', 'shanxi-security-a',
                   'beijing-sanju-environmental', 'ju-hua', 'yongda-group-a', 'quanchai-eng', 'chaohua-tech-a',
                   'oriental-yuhong-a', 'fangsheng-phara', 'shenzhen-jufei-optoelectronics',
                   'shanghai-runda-medical-technology-c', 'sansteel-mg-a', 'china-hi-tech', 'avcon-information-tech',
                   'zhangjiagang-furui-special-equip', 'beijing-wkw-automotive-parts-a', 'hwa-create-corp-ltd',
                   'fuchun-tech', 'yunnan-chihong', 'universal-scie', 'befar-group', 'corun-new-ener', 'xinri-hengli',
                   'huawei-culture', 'zhejiang-jingu-a', 'sh-morn-elec-a', 'well-lead-medical-co-ltd',
                   'yunhai-metals-a', 'hubei-kailong-chemical', 'wanwei-hi-tech', 'dima-industry', 'keda-group',
                   'clou-elect-a', 'yihua-real-est-a', 'zhongtai-chem-a', 'shandong-longda-meat-foodstuff-a',
                   'zhejiang-century-huatong', 'ruize-material-a', 'sun-paper-a', 'suzhou-anjie-technology-a',
                   'joyson-electro', 'beijing-originwater-technology', 'dfd-chemical-a', 'wanda-cinema-line-corp',
                   'honyu-wear-resistant-new-materials', 'lianyungang-po', 'beijing-highlander-digital-technolo',
                   'enjoyor']
ALL_BELOW_21_16 = ['victory-giant-technology-huizhou-co', 'dragon-pipe-a', 'zhejiang-jingsheng-mech-electric',
                   'tj-tianbao-a',
                   'hangzhou-century', 'yantian-port-a', 'dongfang-elec-ss', 'yankon-group', 'avcon-information-tech',
                   'ellington-elec',
                   'hongtu-hi-tech', 'western-securities-a', 'sc-minjiang', 'meihua-holding', 'shen-huo-a',
                   'clou-elect-a',
                   'hengshun-vineg', 'fangxing-sci', 'kstar-science-a', 'shenzhen-cdl-precision',
                   'china-nuclear-engineering-corp-ltd',
                   'yingliu-electr', 'zhejiang-yonggui-electric', 'shanghai-fortune-techgroup', 'qingdao-rural',
                   'tasly-pharmace',
                   'cnnc-hua-yuan-a', 'py-refractories-a', 'zhongheng', 'haoxiangni-a', 'founder-tech',
                   'zhongk-sanhuan-a', 'merro-pharm',
                   'sansteel-mg-a', 'guangshen-rail-ss', 'cashway-tech', 'changshu-ruite-electric', 'gd-advertising-a',
                   'zhongda-group',
                   'danfu-compressor-a', 'zhejiang-jingu-a', 'shandong-rike-chemical', 'yinyi-real-estate-a',
                   'sichuan-road',
                   'guizhou-broadcasting---tv-informati', 'guide-infrared-a', 'oceanwide-holdings-a', 'hisun-pharm',
                   'befar-group',
                   'zj-dilong-a']

ALL_BELOW_21_17 = ['tianqiao-crane-a', 'hebi-janxi-chemical', 'dikang-pharm', 'china-ship', 'hanhe-cable-a',
                   'aerospace-cf', 'hubei-dinglong-chemical', 'dymatic-chemical-a', 'tianshan-wool-a',
                   'china-film-co-ltd', 'sinoma-science-a', 'daqin-railway', 'yunnan-chihong', 'hualu-hs-chem',
                   'huafa-ind', 'dynagreen-evironmental-protection', 'ningbo-bird', 'beijing-sojo-electric-co-ltd',
                   'ju-hua', 'duzhe-publishing---media-co-ltd', 'shenzhen-infinova-ltd', 'chengdu-r-bridge-a',
                   'lugang-science', 'yunnan-copper-a', 'yunhai-metals-a', 'yango-a', 'zhejiang-semir-a',
                   'huawen-media-a', 'pingtan-develop-a', 'china-animal', 'tibet-summit', 'dongxing-securities',
                   'hualing-xingma', 'bank-of-hangzhou-co-ltd', 'beijing-highlander-digital-technolo', 'golden-horse-a',
                   'deluxe-family', 'beijing-taikong-panel', 'beijing-ultrapower-software', 'beijing-jingxi-culture-a',
                   'nanjing-quanxin-cable-tech', 'maanshan-iron-ss', 'great-wall-mot', 'hlj-agricultur',
                   'guanfu-co-ltd-a', 'copote-tech', 'yunnan-xiyi-ind-a', 'sz-shenbao-a', 'nationstar-a',
                   'beijing-egova']
ALL_BELOW_21_18 = ['zhejiang-garden-bio-chemical', 'neptunus-bioen-a', 'huafon-spandex-a',
                   'huafon-microfibre-shanghai-co', 'jinyu-group', 'jishi-media', 'orient-group', 'beyondsoft-a',
                   'cyts-tours', 'dongyangguang', 'yutong-bus', 'humanwell', 'sino-platinum', 'sundiro-a',
                   'aerospace-pwr', 'jianglong-shipbuilding', 'shaoneng-a', 'senyuan-electric-a', 'teba',
                   'shanghai-pharm', 'china-merchant', 'yantai-tayho-a', 'luoyang-longhua-heat-trans-energy',
                   'western-resour', 'xinmin-textile-a', 'hangxin-aviation-technology', 'whirlwind', 'gold-mantis-a',
                   'hc-semitek-corp', 'joincare', 'mls-co-ltd', 'tongji-tech', 'shenzhen-kingsun-science-tech',
                   'huaxicun-a', 'newland-a', 'zhejiang-xinneng-photovoltaic-tech', 'beijing-ctrowell-technology-corp',
                   'lianyungang-po', 'sound-environm-a', 'hwa-create-corp-ltd', 'shenzhen-envicool-tech',
                   'edifier-technology-co-ltd', 'huifeng-agrochem-a', 'sunyes-elec-a', 'oriental-yuhong-a',
                   'changshu-tianyin-electromechan', 'zhixin-elect', 'yasheng-indust', 'splendor-sci-tec-a',
                   'sinovel-wind-g']
ALL_BELOW_21_19 = ['juli-sling-a', 'shenzhen-jiawei-lighting', 'jointown-pharm', 'nanjing-dept', 'wanma-cable-a',
                   'beijing-kunlun-tech', 'tapai-group-a', 'xinke-material', 'sun-paper-a', 'routon-elect',
                   'beijing-originwater-technology', 'honyu-wear-resistant-new-materials', 'tianan-coal', 'julong',
                   'cosco-shipping', 'yihua-real-est-a', 'sinodata-a', 'suzhou-hi-tech', 'yihua-timber',
                   'xiangtan-elec', 'beijing-hezong-science--technology', 'shenzhen-mason-technologies-a',
                   'tianjin-ringpu-bio-tech', 'shanghai-runda-medical-technology-c', 'hz-hangyang-a', 'xinye-textile-a',
                   'focus-lightings-tech', 'fujian-sbs-zipper-science-tech', 'chaodong-cem', 'cn-eagle-electro-a',
                   'lingnan-landscape-co-ltd', 'cofco-property-a', 'xian-dagang-road-machinery-co',
                   'zhongsheng-pharm-a', 'yahgee-house-a', 'nanyang-tech-a', 'yantai-valiant-fine-chemicals-a',
                   'sh-morn-elec-a', 'huawei-culture', 'jinduicheng', 's-yizheng-chem', 'anhui-water',
                   'tangel-publishing', 'heilan-home', 'myhome-real-estate-a', 'bj-centergate-a',
                   'zhuhai-hokai-med-instruments', 'china-shenhua', 'tang-sanyou', 'petro-cn-jinhong-a']
ALL_BELOW_21_20 = ['loncin-motor', 'goldenmax-international-tech-a', 'xin-zhi-motor-a',
                   'focused-photonics-hangzhou-inc', 'haibo', 'gd-guanghong-a', 'beijing-wkw-automotive-parts-a',
                   'dongfang-elect-a', 'liugong-a', 'nine-dragon-a', 'jiangsu-sainty', 'angang-a', 'furi-elec',
                   'shenzhen-sea-star-technology', 'tianjin-global', 'lida-optical-a', 'mz-plastic-a',
                   'sgsg-science-zhuhai', 'yangquan-coal', 'feilo', 'sunyard', 'jianghuai-auto', 'dongfang-therm-a',
                   'sufa-tech-a', 'global-infotech-co-ltd', 'zhongchu', 'beijing-lanxum-tech-co', 'sh-xinhua-medi',
                   'anhui-jingcheng-copper-share-co-ltd', 'bank-of-jiangsu-co-ltd', 'shaanxi-jinye-a', 'suofeiya-a',
                   'yantai-dongcheng-pharmaceutical-co', 'huayi-elec', 'guangdong-dcenti', 'yuancheng-cable-a',
                   'china-merchants-shekou-industrial', 'zhejiang-satellite-petrochem-a', 'beijing-supermap-software',
                   'xin-jiang-hops', 'c-s-paper-a', 'tv---broadcast-a', 'sz-huaqiang-a', 'yongda-group-a',
                   'wuhan-zhongyuan-huadian-sci-tech', 'longjian', 'huajin-chemical-a', 'times-new-mat',
                   'sunsea-telecom-a', 'fujian-longma-equipment']
ALL_BELOW_21_21 = ['shanghai-wondertek-software-corp-lt', 'huading-nylon', 'xian-kaiyuan-a', 'rizhao-port',
                   'jiajia-food-a', 'europol-logistic-a', 'shenzhen-increase-tech-a', 'loften-environmental-a',
                   'xiamen-itg', 'jinxi-axle', 'tellus-a', 'ningbo-united', 'shenzhen-techand-eco-environment',
                   'toyou-feiji-electronics', 'bestv-new-medi', 'greatoo-a', 'navtech-inc', 'gd-chj-industry-a',
                   'fujian-cement', 'buildingresearch-a', 'capital-dev', 'tianlun-a',
                   'jiangsu-changshu-rural-commercial-b', 'sinoma-engine', 'siasun-robot-automation-co',
                   'jieshun-sci-tech-a', 'mesnac-a', 'soyea-a', 'cnlight-a', 'rongji-software-a', 'suntront-tech',
                   'xiamen-tungst', 'baotailong-coa', 'xingrong-invest-a', 'fangda-a', 'minsheng-invest-a',
                   'hiconics-drive-tech-co', 'yueling-a', 'hainan-haide-a', 'hua-xia-bank', 'huafu-melange-a',
                   'wanda-cinema-line-corp', 'gansu-dayu-water-saving-group', 'gold-summit', 'comfort-sci-tech-a',
                   'shanghai-guao-electronic', 'avic-real-estate-a', 'sichuan-xunyou-network-technology-c',
                   'suzhou-keda-technology-co-ltd', 'dongguang-micro-a']
ALL_BELOW_21_22 = ['chongqing-tong-jun-ge-co-ltd', 'shenma-indu', 'phoenix-publ-m', 'cecep-w-p', 'gpro-titanium-a',
                   'sh-ind-develop', 'qinling-cement', 'china-oilfield-ss', 'tianjin-chase-sun-pharmaceutical-co',
                   'east-group', 'kibing-group', 'jilin-power-a', 'bj-unistrong-a', 'nhwa-pharma-a',
                   'shenzhen-changhong-tech', 'dunan-environ-a', 'wiscom-sys-a', 'xiamen-c-d',
                   'jiangsu-tongguang-electronic', 'zhejiang-shibao-a', 'sz-hongtao-a', 'sh-mechanical',
                   'resour-d-c-pha', 'capital-tour', 'dongfeng-auto', 'tong-hua-shuang-long-chemical',
                   'dalian-zeus-entertainment', 'sz-xiongtao-power-tech-a', 'ligeance-mineral-a', 'fuyao-glass',
                   'gaochun-ceram', 'union-hldgs-a', 'zhengping-road-bridge-construction', 'yotrio-group-a',
                   'yuandong-drive-a', 'china-railway', 'linyang-electr', 'longping-tech-a', 'dan-bond-tech-a',
                   'shandong-gettop-acoustic-a', 'delisi-food-a', 'quingdao-port-international', 'ancai-hi-tech',
                   'shanghai-kangda-new-materials-a', 'xizang-haisco-pharmaceutical-a', 'wolong', 'sichuan-jiuzhou-a',
                   'fangda-steel', 'haili-metal-one-a', 'vtron-technologies-ltd']
ALL_BELOW_21_23 = ['baiyun-airport', 'mengdian', 'jilin-jinguan-electric-a', 'hualian-dep-a',
                   'beijing-jiayu-door-window-curtain', 'guangzhou-auto', 'aj-corp', 'zhongyuan-exp', 'zj-kangsheng-a',
                   'qiming-info-tech-a', 'chengdu-huaqi-houpu-holding-co-ltd', 'guangdong-silvere-sci-and-tech',
                   'hebei-changshan-biochem-pharma', 'huang-jinma-a', 'maoye-logistics-a', 'binjiang-re-a',
                   'guoyuan-sec-a', 'luan-env-ener', 'longxing-chemical-stock-co-ltd', 'qinghai-saltlake-a',
                   'wenergy-a', 'lingyun-ind', 'huafang-co', 'csg-holding-a', 'shandong-meichen-science',
                   'hisense-kelon-a', 'sz-universe-a', 'haiyao-a', 'zhejiang-century-huatong', 'hengli-industrial-a',
                   'embedway-shanghai', 'china-hi-tech', 'huasun-group-a', 'sc-nitrocell-a', 'penyao-environmental-a',
                   'talimu-agric', 'suzhou-institute-building', 'huitian-power-a', 'beingmate-a',
                   'anhui-yingjia-distillery-co-ltd', 'changshan-a', 'hailiang-a', 'winnerway-a',
                   'bank-of-guiyang-co-ltd', 'yahua-ind-a', 'anhui-ankai-a', 'wuhan-nusun-landscape',
                   'bank-of-chengdu-a', 'hengyuan-coal', 'chixia-develop']
ALL_BELOW_21_24 = ['xilong-chemical-a', 'chaozhou-three-circle', 'bj-north-star', 'wellhope-agri-tech',
                   'changyuan-elec-a', 'qh-gelatin-a', 'beijing-beilu-pharmaceutical', 'western-metal-a', 'zj-orient',
                   'jiangsu-huahong-technology-co-ltd', 'baoding-heavy-industry-co-ltd', 'kingray-tech',
                   'beijing-thunisoft-co-ltd', 'guangdong-dowstone-tech', 'hangzhou-everfine-photo-e-info',
                   'dingli-communications-corp-ltd', 'beijing-chinese-digital-publis', 'beijing-trs-information-tech',
                   'batian-ecotypic-a', 'beida-jade-bir', 'sanlux-rubber-a', 'dongan-auto', 'xinji-energy',
                   'bright-dairy', 'lanhua-sci-tec', 'yantai-yuanche', 'avic-sanxin-a', 'offshore-oil',
                   'jiangsu-huasheng-tianlong-photo', 'homey-aquatic', 'chengzhi-a', 'chenming-paper-a',
                   'jinggong-steel', 'chitianhua', 'shenzhen-jingquanhua-electronics', 'shahe-ind-a', 'pearl-river-a',
                   'bewinner-comm-a', 'shengli-a', 'wuhan-tianyu-info-industry', 'zhangjiang', 'jangho-curtain',
                   'shentong-valve-a', 'youngor-group', 'china-enter', 'porton-fine-chemicals-ltd', 'hongda-mining',
                   'gci-science---tech-a', 'zy-tungsten-a', 'sh-challenge-a']
ALL_BELOW_21_25 = ['poten-environment-group-co-ltd', 'telling-tele-a', 'suzhou-crystal-clear-chemical',
                   'suzhou-electrical-apparatus-sci', 'baichuan-chem-a', 'xianju-pharm-a', 'jinguyuan-hold-a',
                   'world-union-prop-a', 'huludao-zinc-a', 'chengdu-hongqi-chain-a', 'jiuli-metals-a',
                   'zhangjiagang-furui-special-equip', 'hangxiao-steel', 'guangbo-group-a',
                   'jiangsu-wujiang-rural-commercial-ba', 'shenzhen-topway-a', 'chang-jiang-shipping-phoenix',
                   'goody-science---technology-co-ltd', 'liuzhou-steel', 'tianli-tech', 'shandong-xiantan-co-ltd',
                   'tong-da-cable-a', 'hengxin-mobile-business', 'yabao-pharm', 'tj-motor-dies-a', 'xiwang-foodstuff-a',
                   'taloph-pharm', 'jiangsu-financial-a', 'hengbao-a', 'dongfeng-print', 'zhejiang-jindun-fans',
                   'yuneng-holding-a', 'polymer-biochem-a', 'huazhi-holding-a', 'xinjiang-xuefeng-sci-tech-group-co',
                   'langold-estate-a', 'hengxing-tech-a', 'shenzhen-fluence-tech', 'aeolus', 'edan-instruments-inc',
                   'ght-a', 'royal-group-co-ltd', 'hangzhou-cable-co-ltd', 'hebei-sailhero-environmental',
                   'shanghai-kinlita-chemical-co', 'raisecom-technology-co-ltd', 'fiyta-hold-a', 'xinlong-hold-a',
                   'xingmin-wheel-a', 'chongqing-stee']
ALL_BELOW_21_26 = ['shinva-medical', 'xianmen-xiangy', 'orient-zirconic-a', 'jiangxi-copper-ss',
                   'china-kings-resources-group-co-ltd', 'ningbo-cixing', 'sh-shenhua', 'shanghai-new-culture-media-gr',
                   'kingdomway-group-a', 'kee-ever-bright-decorative', 'jinniu-chem', 'wuxi-hodgen-tech',
                   'fengdong-thermal-a', 'noposion-agro-a', 'beijing-forever-tech', 'maoming-shihua-a',
                   'zhongnan-heavy-a', 'jiuzhitang-a', 'henan-hanwei-electronics-co', 'yawei-machine-a',
                   'beijing-urban', 'beijing-new-oriental-star-petro-eng', 'bode-energy-equipment',
                   'guangdong-macro-co-ltd', 'jingyuntong-te', 'jiangsu-broadcasting-cable-informat',
                   'hexing-electrical-co-ltd', 'qingdao-eastsoft-communic-tech', 'shindoo-chemical-a', 'sc-shuangma-a',
                   'skyworthdt-a', 'gz-friendship-a', 'gospell-digital-tech', 'hunan-jiudian-pharma', 'cnhtc-truck-a',
                   'sz-beauty-star-a', 'shuangxing-matrl-a', 'chuantou-ener', 'markor-furn', 'hengyi-petrochem-a',
                   'pku-healthcare-a', 'dajiang', 'jilin-yatai', 'apeloa-a', 'new-material-a', 'kaimeite-gases-a',
                   'tongfeng', 'shandong-publishing-a', 'nanjing-gaoke', 'songliao-auto']
ALL_BELOW_21_27 = ['jiangsu-jiangyin-bank', 'gi-technologies-beijing', 'sieyuan-electric-a', 'dragon-molybde',
                   'powerway-alloy', 'longshine-tech', 'chengde-lolo-a', 'suzhou-goldengreen-tech', 'shenqi-phar',
                   'jiangsu-zhangjiagang', 'xilinmen-furni', 'guangdong-new-grand-long-packing',
                   'dalian-east-new-energy-develop', 'guangdong-xianglu-tungsten', 'yibin-tianyuan-group-co-ltd',
                   'east-china-engr-a', 'shenda', 'zhejiang-transfar-co-ltd', 'yn-real-estate', 'sinochem', 'meiling-a',
                   'weixing-new-mat-a', 'pinggao-elec', 'cn-xd-electric', 'wasu-media-holdings-a', 'jinbei-automot',
                   'palm-landscape-a', 'central-empor', 'china-cifco-investment', 'urban-const',
                   'shanghai-sunglow-packaging', 'juneyao-airlines-co-ltd', 'pudong-cons',
                   'jiangsu-jingshen-salt---chemical-in', 'yilite', 'zjg-chemic-machi-a',
                   'puyang-huicheng-electronic-material', 'tielong-log', 'sunvim-group-a', 'sd-expressway',
                   'zj-east-crystal-a', 'shanxi-coking', 'chtc-helon', 'dongguan-chitwing-tech', 'henan-lingrui',
                   'masterwork-machinery', 'gehua-catv', 'jiangshan-chem-a', 'shanghai-anoky-group', 'tvzone-media']
ALL_BELOW_21_28 = ['zhejiang-longsheng-auto-parts-co-lt', 'shanghai-xuerong-bio-tech', 'zhejiang-jihua',
                   'jiaozuo-wanfang-aluminum', 'hunan-baili-engineering-sci---tech', 'electro-optic', 'hunan-haili',
                   'netac-tech', 'chongqing-construction-engineering', 'yasha-decoration-a', 'shenzhen-gas',
                   'lutianhua-a', 'anhui-zhongding-a', 'em-technology', 'billions-chemicl-a', 'jsti-group',
                   'rongan-property-a', 'aodong-a', 'zhongcheng-pack-a', 'cheng-da', 'tederic-machinery',
                   'guangdian-elec', 'great-wall-movie-tv-ltd', 'ningbo-orient-wires-and-cables', 'sh-shi-mao',
                   'utour-travel-a', 'hakim-unique-internet', 'qianhong-biophar-a', 'dongyuan-electri-a', 'sz-energy-a',
                   'guochuang-software', 'andon-health-a', 'jinzi-ham-a', 'xiandai-invest-a', 'jiangmen-sugar-a',
                   'golden-dragon-a', 'shanghai-yaoji-playing-card-a', 'huazi-industry', 'inesa-electron',
                   'xinjiang-tianshan-animal', 'nanning-dep', 'guizhou-gas-a', 'jiangmen-kanhoo-industry',
                   'feitian-technologies-co-ltd', 'xinmei', 'guangri-stock', 'guilin-guanglu-a', 'interchina-wat',
                   'baosheng', 'ningbo-xianfeng-new-material']
ALL_BELOW_21_29 = ['yuhuan-cnc-machine', 'sanxing-electr', 'hangzhou-freely-communication', 'zj-haiyue',
                   'sinosteel-tech-a', 'xuguang', 'yaxing-coach', 'shenzhen-institute-building-a', 'tianfu-thermo',
                   'leon-tech', 'zijiang', 'shandong-fin-cnc-machine-co-ltd', 'luxin-venture', 'ningxia-buildi',
                   'newcapec-electronics', 'jiangnan-chemica-a', 'qinhuangdao-port', 'kingdream-a', 'mig-unmobi-tech',
                   'chinese-univer', 'new-beiyang-it-a', 'haers-containers-a', 'sacred-sun-power-a',
                   'zhengzhou-gl-tech-co-ltd', 'xiamen-meiya-pico-information', 'orient-tanta-a', 'zhujiang-brewery-a',
                   'fuling', 'orient-int', 'dalian-power', 'jingneng-power', 'yinhe-hi-tech-a', 'yueyang-paper',
                   'qiangsheng', 'xinhua-winshare-publishing-medi-a', 'hengfeng-information', 'zhong-fu-tong',
                   'dongxin-carbon', 'guangdong-tonze-electric', 'canudilo-fashion-a', 'aoto-electronics-a',
                   'beijing-hanbang-technology-corp', 'atlantic', 'alpha-animation-a', 'sz-sed-ind-a', 'sl-pharm-a',
                   'shanghai-taisheng-wind-power', 'pubang-landscape-architecture-co-lt', 'oceans-king-a',
                   'beijing-qianjing-landscape-co-ltd']
ALL_BELOW_21_30 = ['changbao-steel-a', 'hebei-huijin-electromechanical', 'tianjin-jinbin-development',
                   'liaoning-kelong-fine-chemical', 'guangzhou-jinyi-media', 'hengda-hi-tech-a', 'camel-group',
                   'jiangsu-pacific-quartz-co-ltd', 'changzhou-tiansheng-new-materials', 'teda-a', 'sy-cuihua-gsj-a',
                   'jinjing', 'yingkou-port', 'cred-holding', 'bauing-decoration-a', 'reclaim-constrcn-a',
                   'yunnan-coal-en', 'rainbow-store-a', 'kanion', 'grandland-group-a', 'hailide-a', 'danhua-chem',
                   'changjiang-pu-', 'bj-hualian', 'guangdong-sky-dragon-printing-ink', 'zhongyeda-elec-a',
                   'hangzhou-cncr-it', 'fspg-hi-tech-a', 'jiangsu-guotai-a', 'comix-group-a', 'zhong-tong-bus-a',
                   'keda-indu', 'fuchunjiang-env-a', 'castech-inc-a', 'sinoer-a', 'suzhou-ta-a-ultra-clean',
                   'bj-creative-a', 'besttone-holdi', 'yunnei-power-a', 'bbca-a', 'harbin-boshi-automation-a', 'ikd-a',
                   'jinhe-biotechnology-a', 'tianbao-foods-a', 'hainan-mining-co-ltd', 'ln-sg-automoti',
                   'ningbo-constru', 'yaxia-automobile-a', 'shenergy', 'dazhong-trans']
GUOFANG_BELOW_21 = ['avic-electro-a', 'avic-aircraft-a', 'north-navigati', 'hongdu-avia', 'aero-engine-ctrl-a',
                    'chengfa-tech', 'cn-avic-avioni', 'boyun-new-mat-a', 'beijing-cisri-gaona-materials-tech',
                    'beijing-andawell-a', 'ligeance-mineral-a', 'electro-optic', 'up-optotech-a']
SHARE_LIST_RAW = ALL_BELOW_21_30 + ALL_BELOW_21_29 + ALL_BELOW_21_28 + ALL_BELOW_21_27 + ALL_BELOW_21_26 + \
                 ALL_BELOW_21_25 + ALL_BELOW_21_24 + ALL_BELOW_21_23 + ALL_BELOW_21_22 + ALL_BELOW_21_21 + ALL_BELOW_21_20 + \
                 ALL_BELOW_21_19 + ALL_BELOW_21_18 + ALL_BELOW_21_17 + ALL_BELOW_21_16 + ALL_BELOW_21_15 + \
                 ALL_BELOW_21_14 + ALL_BELOW_21_13 + ALL_BELOW_21_12 + ALL_BELOW_21_11 + \
                 ALL_BELOW_21_10 + ALL_BELOW_21_9 + ALL_BELOW_21_8 + ALL_BELOW_21_7 + ALL_BELOW_21_6 + ALL_BELOW_21_5 + ALL_BELOW_21_4 + \
                 ALL_BELOW_21_3 + ALL_BELOW_21_2 + ALL_BELOW_21_1
SHARE_LIST_ALL = ['tangshan-port', 'soyea-a', 'oceanwide-holdings-a', 'kaiser-china-holding-co-ltd',
                  'east-money-information', 'wuhu-port', 'xinhua-winshare-publishing-medi-a', 'eastcompeace-a',
                  'shandong-fin-cnc-machine-co-ltd', 'baichuan-chem-a', 'great-wall-movie-tv-ltd', 'new-wellful',
                  'huaneng-lancang-river-a', 'mig-unmobi-tech', 'bj-unistrong-a', 'sanan-optoelec', 'sh-shi-mao',
                  'qinhuangdao-port', 'alpha-animation-a', 'juneyao-airlines-co-ltd', 'dalian-zeus-entertainment',
                  'linyang-electr', 'luxi-a', 'western-region-gold-co-ltd', 'yanjing-brewery-a', 'chenzhou-mining-a',
                  'shenghua-biok', 'julong', 'china-cifco-investment', 'shindoo-chemical-a',
                  'gansu-dayu-water-saving-group', 'citic-guoan-a', 'golden-dragon-a', 'gaochun-ceram', 'china-shenhua',
                  'wuhan-ps-information-tech', 'yuguang', 'gezhouba', 'liaoning-kelong-fine-chemical',
                  'zhejiang-jingu-a', 'zhongken-agri', 'navtech-inc', 'canudilo-fashion-a', 'guangdong-macro-co-ltd',
                  'chtc-helon', 'xiamen-c-d', 'heungkong-hold', 'zheshang-securities', 'zhongtian-urban-a',
                  'huachangda-intelligent', 'shandong-iron', 'china-molybden', 'yahgee-house-a',
                  'shenzhen-huapengfei-logistics', 'hangzhou-freely-communication', 'shenwu-environmental-tech',
                  'tianshan-wool-a', 'sungrow-power-supply', 'aero-engine-ctrl-a', 'broadcast---tv',
                  'harbin-gloria-pharmaceuticals', 'qinghai-saltlake-a', 'crystal-optech-a', 'pudong-dev',
                  'anhui-jingcheng-copper-share-co-ltd', 'heilan-home', 'jiuzhitang-a', 'toyou-feiji-electronics',
                  'taloph-pharm', 'zhongchu', 'huaxin-cement', 'b-soft-co-ltd', 'fujian-cement', 'dongan-auto',
                  'fangda-a', 'chengdu-santai-holding-group-co-ltd', 'guochuang-software', 'avic-heavy',
                  'tapai-group-a', 'shanxi-baiyuan-trousers-chain-a', 'jingneng-power', 'harbin-hi-tech',
                  'sumavision-technologies', 'gosuncn-a', 'dan-bond-tech-a', 'xinchao-indust',
                  'well-lead-medical-co-ltd', 'telling-tele-a', 'qingdao-eastsoft-communic-tech', 'danhua-chem',
                  'tianjin-jinbin-development', 'xizang-haisco-pharmaceutical-a', 'anshan-senyuan-road-bridge',
                  'eagle-mining', 'sinochem', 'hailide-a', 'yingkou-port', 'sl-pharm-a', 'buildingresearch-a',
                  'baotailong-coa', 'tv---broadcast-a', 'daqin-railway', 'lanzhou-ls-heavy-equipment-co',
                  'shenzhen-sdg-information-co-ltd', 'tellhow', 'western-resour', 'shaanxi-jinye-a', 'fujian-superpipe',
                  'yunnei-power-a', 'teda-a', 'hongda-xingye-a', 'shanghai-kangda-new-materials-a', 'ght-a',
                  'shenzhen-sunline-tech', 'jiangsu-sanyou-group-co-ltd', 'cs-zoomlion-a', 'kingenta-eco-a',
                  'sh-xinhua-medi', 'jiangshan-chem-a', 'xianmen-xiangy', 'lanhua-sci-tec', 'penyao-environmental-a',
                  'wanma-cable-a', 'denghai-seeds-a', 'dali-technology-a', 'kingdomway-group-a', 'anhui-zhongding-a',
                  'henan-kedi-dairy-industry-co-ltd', 'jieshun-sci-tech-a', 'shengda-mining-a', 'haige-communicat-a',
                  'xiwang-foodstuff-a', 'bbca-a', 'hengli-industrial-a', 'dunhuang-seed', 'yilite',
                  'huafon-microfibre-shanghai-co', 'china-animal', 'shenzhen-sunwin-intelligent', 'dongfang-elect-a',
                  'nationstar-a', 'china-ship', 'central-china-securities-co-ltd', 'jiangsu-sainty',
                  'guangdong-huasheng-electrical-a', 'metallurgical', 'agri-bank-of-c', 'tielong-log', 'n.-china-pharm',
                  'shandong-gettop-acoustic-a', 'times-new-mat', 'everbright', 'valin-steel-a', 'hisoar-pharm-a',
                  'suzhou-crystal-clear-chemical', 'longjian', 'xiamen-tungst', 'ningbo-orient-wires-and-cables',
                  'tong-hua-shuang-long-chemical', 'jsti-group', 'junzheng-ene-c', 'zhongzhu-holdi', 'boyun-new-mat-a',
                  'sichuan-troy-information-tech', 'shanxi-zhendong-pharmaceutical', 'sinotex-invest',
                  'janus-dongguan-precision', 'jilin-jinguan-electric-a', 'yili-energy', 'vtron-technologies-ltd',
                  'qingdao-haier', 'hunan-baili-engineering-sci---tech', 'whirlwind', 'bode-energy-equipment',
                  'beijing-hezong-science--technology', 'aerospace-elec', 'beijing-jingxi-culture-a', 'hisun-pharm',
                  'shenzhen-liantronics', 'shanghai-yaoji-playing-card-a', 'edan-instruments-inc', 'bank-of-comm',
                  'minsheng-invest-a', 'liugong-a', 'zhejiang-semir-a', 'sunwoda-electronic', 'bestv-new-medi',
                  'pgvt-a', 'meidu', 'ming-yang-smart-energy-group', 'chenming-paper-a', 'ningbo-yak-tech-a',
                  'xiamen-meiya-pico-information', 'industrial-sec', 'grandland-group-a', 'hengxin-mobile-business',
                  'huajin-chemical-a', 'taigang-a', 'sh-morn-elec-a', 'hangzhou-shunwang-tech',
                  'titan-wind-energy-suzhou', 'beijing-thunisoft-co-ltd', 'yunnan-chihong', 'tianshan-cemen-a',
                  'hubei-dinglong-chemical', 'gohigh-data-a', 'int-industry-a', 'nationz-technologies-inc',
                  'shangfeng-cement-a', 'shuangxing-matrl-a', 'wenergy-a', 'wuhan-tianyu-info-industry', 'jinyu-group',
                  'chongqing-tong-jun-ge-co-ltd', 'ikd-a', 'chongqing-stee', 'western-mining-co', 'pangda-automob',
                  'beyondsoft-a', 'keda-group', 'zhongjin-a', 'zhejiang-jihua', 'realcan-pharm-a', 'bj-hualian',
                  'guangdong-xianglu-tungsten', 'new-beiyang-it-a', 'chinalin-securities', 'zhejiang-transfar-co-ltd',
                  'hyron-software-a', 'huaxi-securities-a', 'cnlight-a', 'changbao-steel-a', 'orient-securities-co-ltd',
                  'anhui-shenjian-new-materials-co-ltd', 'jiangsu-jingshen-salt---chemical-in', 'kingray-tech',
                  'western-securities-a', 'wellhope-agri-tech', 'shenzhen-techand-eco-environment', 'ningbo-united',
                  'chongqing-construction-engineering', 'hwa-create-corp-ltd', 'hualu-hs-chem', 'yantai-yuanche',
                  'aj-corp', 'quanchai-eng', 'beijing-andawell-a', 'bi-of-oriental-nations', 'sz-topband-a',
                  'dunan-environ-a', 'pinggao-elec', 'shanghai-pharm', 'sanxing-electr', 'dymatic-chemical-a',
                  'zhongk-sanhuan-a', 'sz-airport-a', 'embedway-shanghai', 'xin-jiang-hops', 'zijiang',
                  'bank-of-guiyang-co-ltd', 'cn-shipbuildin', 'sz-woer-a', 'kaile', 'cpt-tech-group-a', 'dragon-pipe-a',
                  'advanced-a', 'chinese-univer', 'suplet-power', 'sh-jiabao', 'dr.-peng', 'zhejiang-runtu-a',
                  'huifeng-agrochem-a', 'new-hope-liuhe-a', 'eastern-comms', 'deluxe-family', 'yinge',
                  'dongguan-kingsun-optoelectron-a', 'sinosteel-tech-a', 'jpmf-guangdong-a', 'shenzhen-h-t-a',
                  'chengdu-huaqi-houpu-holding-co-ltd', 'aluminium-corp', 'yangquan-coal', 'dongguan-eontec',
                  'suntront-tech', 'new-material-a', 'guoyuan-sec-a', 'ningxia-buildi', 'susino-umbrella-a',
                  'jiangsu-nata-opto-electr-material', 'xingmin-wheel-a', 'shuang-ta-food-a', 'chengdu-hongqi-chain-a',
                  'huajing', 'sieyuan-electric-a', 'yabao-pharm', 'weixing-new-mat-a', 'zj-orient', 'china-enter',
                  'chitianhua', 'zj-kangsheng-a', 'shenzhen-topway-a', 'zhongtai-chem-a', 'nanning-dep',
                  'dongguan-chitwing-tech', 'resour-d-c-pha', 'nanjing-steel', 'wiscom-sys-a',
                  'shanghai-taisheng-wind-power', 'sh-ind-develop', 'sz-capstone-a', 'avic-real-estate-a',
                  'orient-tanta-a', 'shanghai-fortune-techgroup', 'shanxi-security-a', 'atlantic', 'icbc-ss',
                  'sh-electric-ss', 'avcon-information-tech', 'soochow-securi', 'dikang-pharm',
                  'tianguang-fire-fighting-co-ltd', 'winnerway-a', 'nari-tech', 'zhejiang-sanhua-co-ltd', 'heihua',
                  'yantai-tayho-a', 'bj-north-star', 'shanghai-runda-medical-technology-c', 'datang-telecom',
                  'fengdong-thermal-a', 'china-railway', 'feilo-acoustic', 'gcl-system-integration-technology',
                  'roshow-technology-co-ltd', 'goody-science---technology-co-ltd', 'bank-of-hangzhou-co-ltd',
                  'gd-advertising-a', 'yifan-xinfu-a', 'zj-east-crystal-a', 'east-group', 'dongfang-precisn-a',
                  'east-china-engr-a', 'longxing-chemical-stock-co-ltd', 'huaren-pharma', 'hongdu-avia',
                  'shinva-medical', 'sacred-sun-power-a', 'shandong-xiantan-co-ltd', 'hongtu-hi-tech',
                  'china-nuclear-engineering-corp-ltd', 'cn-commu-cons', 'huazhi-holding-a', 'hongda-mining',
                  'beijing-egova', 'changjiang-pu-', 'tronly-new-electron-materials', 'guoguang-elec-a',
                  'fj-nanping-sun-a', 'xilinmen-furni', 'zhong-tong-bus-a', 'caitong-securities', 'ningbo-constru',
                  'yantai-dongcheng-pharmaceutical-co', 'shandong-publishing-a', 'holitech-technology-co-ltd',
                  'powerway-alloy', 'maling', 'yuandong-drive-a', 'cn-coal-energy', 'tianfu-thermo', 'jiangsu-dagang-a',
                  'guilin-guanglu-a', 'shenglu-telecom-a', 'leon-tech', 'maoming-shihua-a', 'greatoo-a',
                  'inesa-electron', 'yawei-machine-a', 'beida-jade-bir', 'wuzhou-comm', 'xinyu-iron', 'cnhtc-truck-a',
                  'join-cheer-soft-a', 'bj-capital', 'kingteller-tech-a', 'beijing-vrv-software-corp-ltd', 'navinfo-a',
                  'grg-banking-equipment-co-ltd', 'hainan-mining-co-ltd', 'cn-first-heavy', 'zhongnan-heavy-a',
                  'boomsense-tech', 'tianjin-chase-sun-pharmaceutical-co', 'sailun', 'focus-lightings-tech',
                  'sz-universe-a', 'wasu-media-holdings-a', 'akcome-solar-a', 'xj-goldwind-a', 'kstar-science-a',
                  'yunsheng', 'palm-landscape-a', 'orient-landscape-a', 'guosen-securities-co-ltd', 'rainbow-store-a',
                  'zijin-mining', 'interchina-wat', 'zhejiang-shibao-a', 'zhongjin-gold', 'kingsignal-tech',
                  'shenzhen-dvision-video-communica', 'zhengtong-elec-a', 'beijing-highlander-digital-technolo',
                  'fiyta-hold-a', 'fujian-snowman-a', 'cnnc-hua-yuan-a', 'yango-a',
                  'shanghai-wondertek-software-corp-lt', 'nanjing-quanxin-cable-tech', 'shenzhen-xinguodu-tech',
                  'gd-guanghong-a', 'konka-a', 'gi-technologies-beijing', 'fuchun-tech', 'faw-car-a', 'jingyuntong-te',
                  'jiangxi-copper-ss', 'xinri-hengli', 'cssc-steel', 'shanghai-kinlita-chemical-co', 'citic-heavy-in',
                  'huayi-brothers-media-corp', 'shenzhen-gas', 'yaxia-automobile-a', 'zhejiang-jingsheng-mech-electric',
                  'sun-paper-a', 'china-tianying-inc', 'eternal-asia-a', 'v-v-food---bev',
                  'shenwan-hongyuan-group-co-ltd', 'fangda-steel', 'shenzhen-tianyuan-dic-info-tech',
                  'sinoma-science-a', 'sh-intl-port', 'sinotrans-a', 'suzhou-ta-a-ultra-clean', 'tecon-animal-a',
                  'ourpalm', 'central-empor', 'first-capital-securities-a', 'tiancheng', 'tianqiao-crane-a',
                  'guangdong-tonze-electric', 'jiangsu-wujiang-rural-commercial-ba', 'qianhong-biophar-a',
                  'jinggong-steel', 'lianyungang-po', 'humanwell', 'qingdao-rural', 'chengfa-tech', 'gpro-titanium-a',
                  'sealand-securiti-a', 'hiconics-drive-tech-co', 'hisense-kelon-a', 'binjiang-re-a',
                  'lingnan-landscape-co-ltd', 'huazi-industry', 'youngor-group', 'harbin-boshi-automation-a',
                  'billions-chemicl-a', 'fujian-longma-equipment', 'tongji-tech', 'zh-semicon-a', 'rongtai',
                  'sc-nitrocell-a', 'bright-dairy', 'sgis-a', 'shandong-longda-meat-foodstuff-a', 'sinoma-engine',
                  'hebei-huijin-electromechanical', 'shaanxi-heimao', 'foton-motor', 'nanjing-dept', 'tianli-tech',
                  'dongyangguang', 'veken-elite', 'yn-germanium-a', 'bewinner-comm-a', 'hlj-agricultur',
                  'sunyes-elec-a', 'zhongchangmari', 'huatai-securit', 'avic-aircraft-a', 'beijing-bank',
                  'united-network', 'haite-high-tech-a', 'great-wall-com-a', 'huatian-tech-a',
                  'kee-ever-bright-decorative', 'zhuhai-orbita-control-eng', 'jilin-power-a', 'sz-shenbao-a',
                  'beijing-enlight-media', 'guangdong-bobaolon-co-ltd', 'sy-cuihua-gsj-a', 'cred-holding',
                  'guofeng-plast-a', 'jinjing', 'focused-photonics-hangzhou-inc', 'shenzhen-jufei-optoelectronics',
                  'beijing-qianjing-landscape-co-ltd', 'sc-shuangma-a', 'jiangsu-tongguang-electronic',
                  'suzhou-anjie-technology-a', 'surekam-a', 'anhui-water', 'chongqing-lummy-pharmaceutical',
                  'cts-logistics', 'changchun-dep', 'zj-haiyue', 'brilliance-tech',
                  'xinjiang-xuefeng-sci-tech-group-co', 'bj-creative-a', 'honyu-wear-resistant-new-materials',
                  'ping-an-bank-a', 'sh-mechanical', 'changan-auto-a', 'zhejiang-xinneng-photovoltaic-tech', 'conba',
                  'dakang-farming-a', 'qiangsheng', 'jinniu-chem', 'jiangmen-sugar-a', 'beijing-ultrapower-software',
                  'sh-dazhong', 'shahe-ind-a', 'jinxinnong-feed-a', 'cn-chemical', 'jointown-pharm',
                  'dingli-communications-corp-ltd', 'shenergy', 'longshine-tech', 'hua-xia-bank', 'huaying-agri-a',
                  'huludao-zinc-a', 'xinjiang-tianshan-animal', 'petrochina-ss', 'aeolus', 'guanghui-energ',
                  'guangshen-rail-ss', 'ningbo-cixing', 'dima-industry', 'citic-helicop-a', 'zhejiang-kan-a',
                  'henan-lingrui', 'jinbei-automot', 'taiji-indust', 'shenzhen-mason-technologies-a', 'merro-pharm',
                  'zhejiang-yonggui-electric', 'gem-year-ind', 'guangzhou-ship', 's-beiya-ind', 'kangqiang-elect-a',
                  'jiangsu-jiangyin-bank', 'hainan-airline', 'loften-environmental-a', 'netac-tech', 'guangdong-dcenti',
                  'yingliu-electr', 'zhejiang-jinke-peroxides-co-ltd', 'yantai-valiant-fine-chemicals-a',
                  'china-harzone-industry', 'yuancheng-cable-a', 'huadong-tech-a', 'xiangtan-elec',
                  'wuhan-zhongyuan-huadian-sci-tech', 'techo-telecom-a', 'baiyin-nonferrous-group-co-ltd',
                  'ccoop-group', 'shanghai-kingstar-winning-software', 'yanzhou-coal', 'sunsea-telecom-a', 'feilo',
                  'merchants-ship', 'huaye', 'microelect', 'tvzone-media', 'dongbao-pharm', 'baotou-steel',
                  'fenghuo-elec-a', 'aerospace-cf', 'hand-enterprise-solutions-co', 'start-group', 'zixin-pharm-a',
                  'noposion-agro-a', 'zhejiang-garden-bio-chemical', 'lander-real-estate-co-ltd',
                  'jiangsu-huahong-technology-co-ltd', 'newcapec-electronics', 'sz-ch-bicycle-a', 'ln-sg-automoti',
                  'neptunus-bioen-a', 'changhong-elec', 'tianjin-global', 'bank-of-chengdu-a', 'cn-citic-bank',
                  'china-film-co-ltd', 'newland-a', 'guangdong-hongda-blasting-a', 'bbmg-corp', 'guanfu-co-ltd-a',
                  'xinan-chemical', 'jiangsu-dewei-materials', 'sinoer-a', 'huawen-media-a', 'raas-blood-a',
                  'befar-group', 'xinlong-hold-a', 'baiyun-airport', 'cyts-tours', 'shenzhen-institute-building-a',
                  'xinye-textile-a', 'liuzhou-steel', 'danfu-compressor-a', 'wuhan-fingu-a', 'shanying-paper',
                  'chengdu-corpro-technology-co-ltd', 'china-great-wall', 'kibing-group', 'beijing-urban',
                  'sound-environm-a', 'bauing-decoration-a', 'tibet-summit', 'guangtai-equip-a', 'jishi-media',
                  'boe-technology-a', 'goertek-a', 'dongxin-carbon', 'jiuli-metals-a', 'pingtan-develop-a',
                  'shenzhen-refond-optoelectronics', 'quingdao-port-international', 'xiamen-itg', 'lifan-industry',
                  'shenzhen-infogem', 'ba-yi-steel', 'yunnan-tin-a', 'zhejiang-longsheng-auto-parts-co-lt',
                  'anhui-great-wall-military-industry', 'brother-enterpri-a', 'yatai-pharm-a', 'humon-smelting-a',
                  'hebei-changshan-biochem-pharma', 'nanjing-securities-co', 'yueyang-paper', 'fengle-seed-a',
                  'oriental-yuhong-a', 'rongan-property-a', 'nanyang-tech-a', 'zheguangsha', 'pci-suntek-tec',
                  'nhwa-pharma-a', 'electro-optic', 'cn-power-const', 'hengbao-a', 'guangdong-sky-dragon-printing-ink',
                  'yasheng-indust', 'yuanxing-energy-a', 'fuling', 'huasun-group-a', 'jiangxi-cement-a',
                  'utour-travel-a', 'zheneng-elec-p', 'merchant-express-a', 'china-east-air-ss', 'hailiang-a',
                  'hytera-communica-a', 'ningbo-xianfeng-new-material', 'yunnan-alumin-a', 'sc-minjiang',
                  'science-city-a', 'shaanxi-coal', 'haoxiangni-a', 'hunan-er-kang-pharmaceutical',
                  'zhejiang-jindun-fans', 'shenzhen-mys-a', 'xinhu-zhongbao', 'huang-jinma-a',
                  'anhui-yingjia-distillery-co-ltd', 'raisecom-technology-co-ltd', 'hz-hangyang-a',
                  'jiangsu-zijin-rural-commercial-bank', 'keybridge-com-a', 'new-sea-union-a', 'zhixin-elect',
                  'shandong-meichen-science', 'union-hldgs-a', 'gospell-digital-tech', 'lecron-energy-saving-materials',
                  'beijing-lanxum-tech-co', 'huafon-spandex-a', 'ju-hua', 'beijing-jiayu-door-window-curtain',
                  'beijing-cisri-gaona-materials-tech', 'capital-tour', 'tongfang', 'hongxing-steel',
                  'hengda-hi-tech-a', 'new-century-a', 'xibei-bearing-a', 'jiangsu-jin-tong-ling-fluid-mach',
                  'yasha-decoration-a', 'guide-infrared-a', 'xuzhou-wuyang-technology', 'js-kingfield-a',
                  'jiangsu-huasheng-tianlong-photo', 'china-merchant', 'csr-corp', 'dongfeng-auto',
                  'centre-testing-intl-shenzhen', 'huitian-power-a', 'kunming-pharm', 'yihua-real-est-a',
                  'universal-scie', 'beijing-miteno-communication', 'rongji-software-a', 'beijing-kunlun-tech',
                  'chengxing-chem', 'hebei-sailhero-environmental', 'yahua-ind-a', 'gold-mantis-a',
                  'hongta-securities-co-ltd', 'sino-platinum', 'victor-on-text-a',
                  'victory-giant-technology-huizhou-co', 'sz-energy-a', 'haili-metal-one-a', 'yangtze-power',
                  'masterwork-machinery', 'sichuan-jiuzhou-a', 'tianjin-ringpu-bio-tech', 'lugang-science',
                  'chuantou-ener', 'suzhou-tianma-specialty-chem', 'beijing-beilu-pharmaceutical',
                  'xian-dagang-road-machinery-co', 'sgsg-science-zhuhai', 'henan-hanwei-electronics-co',
                  'besttone-holdi', 'insigma', 'grinm-material', 'nt-microelectron-a', 'ningbo-tech-a', 'hunan-haili',
                  'ganfeng-lithium-a', 'sichuan-xunyou-network-technology-c', 'tang-sanyou', 'shenzhen-terca-a',
                  'freetrade-tech', 'sz-zero-seven-a', 'markor-furn', 'zhangjiagang-furui-special-equip',
                  'guotai-junan-securities-co-ltd', 'gd-chj-industry-a', 'hebi-janxi-chemical', 'hualing-xingma',
                  'haiyao-a', 'dongfang-elec-ss', 'zhejiang-firstar-panel-tech', 'dahua-tech-a',
                  'china-publishing-media', 'shaoneng-a', 'leyard-optoelectronic', 'xuguang', 'guangzhou-jinyi-media',
                  'cecep-w-p', 'zhonghang-electronic-measuring-inst', 'songliao-auto', 'jinjian-cereal',
                  'jinjia-printing-a', 'zhuhai-hokai-med-instruments', 'sufa-tech-a', 'maanshan-iron-ss',
                  'joyson-electro', 'tianma-microelec-a', 'sz-coship-elect-a', 'huaneng-power',
                  'chang-jiang-shipping-phoenix', 'edifier-technology-co-ltd', 'huaan-securities-co-ltd',
                  'zhejiang-huatie-construction-safety', 'jingui-silver-a', 'ellington-elec', 'routon-elect',
                  'wintime-energy', 'tiandi-tech', 'ygsoft-a', 'yunnan-coal-en', 'china-cosco', 'phoenix-publ-m',
                  'sz-sunlord-elec-a', 'qinling-cement', 'baoshuo', 'lingyun-ind', 'tasly-pharmace', 'shenda',
                  'tongfeng', 'myhome-real-estate-a', 'lens-technology-co-ltd', 'dhc-software-a',
                  'guangdong-new-grand-long-packing', 'zhongcheng-pack-a', 'longsheng', 'shandong-rike-chemical',
                  'tontec-tech', 'teba', 'poten-environment-group-co-ltd', 'sz-sed-ind-a',
                  'shenzhen-fenda-technology-a', 'shanghai-const', 'sichuan-road', 'loncin-motor',
                  'guizhou-broadcasting---tv-informati', 'ancai-hi-tech', 'zhongda-group', 'cn-metal-eng-a',
                  'dalian-east-new-energy-develop', 'china-national-nuclear-power-co-ltd', 'sz-huaqiang-a', 'greattown',
                  'zhenjiang-dongfang-electric-heat', 'jangho-curtain', 'suzhou-good-ark-a', 'beijing-jetsen-tech-co',
                  'fujian-sbs-zipper-science-tech', 'cofco-property-a', 'tong-da-cable-a', 'sz-beauty-star-a',
                  'xinji-energy', 'tianjin-pengling-rubber-hose', 'sz-textile-a', 'yinyi-real-estate-a', 'sundiro-a',
                  'changjiang-ele', 'comix-group-a', 'strong-year', 'hengkang-medical-a', 'shanxi-coking',
                  'cn-railway-grp', 'yinhe-hi-tech-a', 'goworld-a', 'zongshen-power-a', 'sunbird-yacht',
                  'hualian-dep-a', 'yq-sea-cucumber-a', 'hangzhou-cncr-it', 'hexing-electrical-co-ltd',
                  'hengfeng-information', 'net263-a', 'zhongyeda-elec-a', 'dajiang', 'luxin-venture', 'jilin-yatai',
                  'hangxiao-steel', 'shanghai-anoky-group', 'qiming-info-tech-a', 'fuyao-glass',
                  'bank-of-jiangsu-co-ltd', 'beijing-forever-tech', 'gehua-catv', 'suzhou-hi-tech', 'faw-xiali-a',
                  'shenzhen-yitoa-intelligent-control', 'anxin-trust', 'shenzhen-kaifa-a', 'jiaozuo-wanfang-aluminum',
                  'huaxicun-a', 'hi-target-navigation-tech-co', 'changzhou-tiansheng-new-materials', 'guangdian-elec',
                  'jilong-gold', 'zhejiang-century-huatong', 'europol-logistic-a', 'gz-friendship-a', 'xinmei',
                  'mesnac-a', 'senyuan-electric-a', 'zhejiang-med', 'jinfeng-invest', 'rongsheng-a', 'hebei-steel-a',
                  'guangri-stock', 'xiandai-invest-a', 'western-metal-a', 'huafang-co', 'orient-group',
                  'hainan-zhenghe', 'zj-dilong-a', 'erfangji', 'wuhu-token-sciences', 'nanjing-panda',
                  'zhongsheng-pharm-a', 'guangdong-silvere-sci-and-tech', 'beijing-originwater-technology',
                  'shenzhen-riland-industry-co', 'misho-ecology-landscape', 'corun-new-ener', 'jiangsu-financial-a',
                  'zhong-fu-tong', 'csg-holding-a', 'gold-summit', 'huilong-agri-pro-a', 'dabeinong-tech-a',
                  'xuzhou-combustion-control-tech', 'beijing-trs-information-tech', 'py-refractories-a',
                  'changyuan-elec-a', 'wuhan-nusun-landscape', 'sinovel-wind-g', 'taiya-shoes-co-ltd',
                  'xinmao-sci-tech-a', 'dragon-molybde', 'clou-elect-a', 'shunrong-auto-a', 'ningbo-huaxiang-a',
                  'lujiazui', 'haers-containers-a', 'huafu-melange-a', 'zhejiang-satellite-petrochem-a',
                  'beijing-taikong-panel', 'dongfang-therm-a', 'zhongyuan-exp', 'jihua-group', 'kanion',
                  'pubang-landscape-architecture-co-lt', 'chengdu-techcent-environment', 'shaanxi-trust-a',
                  'kingdream-a', 'beijing-hanbang-technology-corp', 'reclaim-constrcn-a', 'juli-sling-a',
                  'qh-gelatin-a', 'suofeiya-a', 'shandong-mining-a', 'aerospace-h-tech-a',
                  'china-kings-resources-group-co-ltd', 'jinguyuan-hold-a', 'maoye-logistics-a', 'rizhao-port',
                  'angang-a', 'beijing-wkw-automotive-parts-a', 'huafa-ind', 'copote-tech',
                  'xinjiang-machinery-research-inst', 'dalian-power', 'twin-tower-a', 'xinke-material',
                  'bank-of-suzhou', 'tatwah-smartech-co-ltd', 'jiangxi-zhengbang-technology-co-ltd',
                  'liaoning-hongyang', 'offshore-oil', 'shaanxi-jr-fire-protection', 'air-china-ss', 'shenzhen-mtc-a',
                  'china-hi-tech', 'shenzhen-cdl-precision', 'tianlun-a', 'suzhou-jinfu-new-material-co',
                  'xishan-coal-a', 'meiling-a', 'sz-hongtao-a', 'sinolink-sec', 'ligeance-mineral-a', 'jinzi-ham-a',
                  'sh-shenhua', 'c-s-paper-a', 'shenzhen-ysstech-info-tech', 'risesun-real-est-a', 'broad-ocean-a',
                  'shenzhen-kingsun-science-tech', 'chaohua-tech-a', 'zz-mining-mach', 'jiangxi-huawu-brake',
                  'yonghui-stores', 'oceans-king-a', 'linewell-software-co-ltd', 'shentong-valve-a', 'aerospace-pwr',
                  'beijing-etrol-tech', 'chengzhi-a', 'hengshun-vineg', 'tengda-constr',
                  'puyang-huicheng-electronic-material', 'great-wall-mot', 'gemdale', 'huizhou-speed-wireless',
                  'guangbo-group-a', 'yibin-tianyuan-group-co-ltd', 'victoryprecision-a', 'jiangnan-chemica-a',
                  'shenqi-phar', 'sd-expressway', 'hangzhou-cable-co-ltd', 'talimu-agric', 's-yizheng-chem',
                  'changshu-ruite-electric', 'southern-air', 'ruize-material-a', 'das-intellitech-a',
                  'beijing-shouhang-resou-saving-a', 'bank-of-nanjin', 'beifang-chuang', 'tongwei', 'haibo',
                  'sh-challenge-a', 'wanwei-hi-tech', 'tianyuan-tech-a', 'gold-seed-wine', 'jinhe-biotechnology-a',
                  'tj-motor-dies-a', 'dongyuan-electri-a', 'suzhou-goldengreen-tech',
                  'luoyang-longhua-heat-trans-energy', 'norinco-a', 'shanghai-guao-electronic', 'founder-tech',
                  'shenzhen-gongjin-electronics', 'sw-securities', 'guangdong-hongteo-accurate-tech',
                  'shenzhen-tatfook-tech', 'kyland-tech', 'sichuan-gaojin-a', 'zhiguang-elec-a', 'wanxiang-donee',
                  'xilong-chemical-a', 'petro-cn-jinhong-a', 'yaxing-coach', 'qilianshan', 'jinling', 'shenzhen-seg-a',
                  'rare-earth', 'liuguo-chem', 'neusoft-corp', 'fuchunjiang-env-a', 'founder-securi', 'changyuan',
                  'chinese-town-a', 'chaodong-cem', 'fangsheng-phara', 'tellus-a', 'jiangsu-shagang-a',
                  'baoan-real-estate-a', 'zhengzhou-gl-tech-co-ltd', 'huakong-seg-a', 'hebang-corp', 'huafang',
                  'jianglong-shipbuilding', 'zjg-chemic-machi-a', 'renhe-pharm-a', 'ronghua-ind', 'yn-real-estate',
                  'tdg-holding', 'polymer-biochem-a', 'linzhou-mach-a', 'chengdu-r-bridge-a', 'yunnan-xiyi-ind-a',
                  'nanfang-pump-industry', 'jinxi-axle', 'fangxing-sci', 'jidong-cement-a', 'jiangsu-hoperun-software',
                  'batian-ecotypic-a', 'gf-securities-a', 'chengdu-xiling-power-a', 'red-arrow-a',
                  'shenzhen-jingquanhua-electronics', 'suzhou-keda-technology-co-ltd', 'world-union-prop-a',
                  'zhongtian-tech', 'china-baoan-group-co-ltd', 'shenzhen-fluence-tech', 'yin-he-elec-a',
                  'guizhou-tyre-a', 'fspg-hi-tech-a', 'tederic-machinery', 'taier-heavy-ind-a', 'nine-dragon-a',
                  'nantong-metalforming-equipment', 'selen-sci-tech-a', 'dalian-huarui-heavy-industry-a',
                  'beijing-chinese-digital-publis', 'topraysolar-a', 'xingfa-chem', 'yuhuan-cnc-machine',
                  'aerospace-auto', 'bomin-electronics-co-ltd', 'org-packaging-a', 'andon-health-a', 'softto-a',
                  'aoto-electronics-a', 'pearl-river-a', 'lida-optical-a', 'zy-tungsten-a', 'huawei-culture',
                  'beijing-sojo-electric-co-ltd', 'skyworthdt-a', 'sinodata-a', 'hedy-holding-a', 'bj-centergate-a',
                  'ht-opticelectr', 'homey-aquatic', 'canny-elevator-a', 'cn-avic-avioni', 'dmegc-magnetics-a',
                  'southwest-phar', 'bluedon-info-security-tech', 'rastar-group', 'suzhou-electrical-apparatus-sci',
                  'cosco-shipping', 'yankon-group', 'enjoyor', 'shenyang-mach-a', 'hc-semitek-corp', 'sunnada-comm-a',
                  'kaimeite-gases-a', 'pudong-cons', 'ctv-media', 'huahai-pharma', 'yueling-a', 'cheng-da',
                  'chunxing-pre-mec-a', 'jiangmen-kanhoo-industry', 'shanghai-new-culture-media-gr', 'mengdian',
                  'hubei-biocause-pharmaceutical', 'shenma-indu', 'cn-eagle-electro-a', 'souyute-fashion-a',
                  'mz-plastic-a', 'dalian-daxian', 'beijing-philisense-tech', 'shen-huo-a', 'shenzhen-changhong-tech',
                  'tj-tianbao-a', 'dynagreen-evironmental-protection', 'chaozhou-three-circle', 'luan-env-ener',
                  'guanlu-a', 'joincare', 'hengyuan-coal', 'yihua-timber', 'jiangsu-welle-environmental',
                  'yunnan-copper-a', 'beijing-sinnet-tech', 'eastern-investment-a', 'invengo-a',
                  'suzhou-institute-building', 'porton-fine-chemicals-ltd', 'global-infotech-co-ltd', 'northeast-sec-a',
                  'guizhou-gas-a', 'goldenmax-international-tech-a', 'xin-zhi-motor-a',
                  'beijing-jiaxun-feihong-electrical', 'hengxing-tech-a', 'camel-group', 'yantian-port-a',
                  'o-film-tech-a', 'shenzhen-everwin-precision-tech', 'sunyard', 'railway-signal-communication-ltd',
                  'jinduicheng', 'langold-estate-a', 'mls-co-ltd', 'yotrio-group-a', 'aerospace-comm', 'meihua-holding',
                  'gd-power', 'duzhe-publishing---media-co-ltd', 'guangdong-dowstone-tech', 'dayuan-chem',
                  'shenzhen-increase-tech-a', 'jian-feng-chem-a', 'suning-commerce-a', 'chengde-lolo-a', 'cashway-tech',
                  'gold-jade', 'huadian-power', 'harbin-hatou', 'furi-elec', 'hubei-kailong-chemical', 'guangzhou-auto',
                  'sz-xiongtao-power-tech-a', 'shanghai-kinetic-medical-co', 'avic-sanxin-a', 'cgn-power',
                  'jiangsu-changshu-rural-commercial-b', 'unilumin', 'xiamen-anne-corp-ltd',
                  'shenzhen-sea-star-technology', 'guangzheng-steel-a', 'jiangsu-zhangjiagang', 'nanjing-gaoke',
                  'hangzhou-everfine-photo-e-info', 'beijing-supermap-software', 'golden-horse-a',
                  'netposa-technologies-ltd', 'meiyan-jixiang', 'yantai-zhenghai-magnetic-mat', 'cn-xd-electric',
                  'sunvim-group-a', 'zhenhua-tech-a', 'zhongnan-cons-a', 'sinosun-tech', 'shanxi-coal', 'castech-inc-a',
                  'apeloa-a', 'orient-int', 'gci-science---tech-a', 'jingxin-pharm-a', 'hangzhou-century', 'keda-indu',
                  'lutianhua-a', 'shengli-a', 'jiajia-food-a', 'zhangjiang', 'zhongheng', 'huading-nylon',
                  'talkweb-info-sys-a', 'elefirst-science-tech', 'wuxi-hodgen-tech', 'china-galaxy-securities-co-ltd',
                  'orient-zirconic-a', 'shenzhen-infinova-ltd', 'jinhua-chemical-a', 'china-oilfield-ss',
                  'shenzhen-envicool-tech', 'royal-group-co-ltd', 'siasun-robot-automation-co',
                  'china-merchants-shekou-industrial', 'jiangxi-sanchuan-water-meter', 'baoshan-steel',
                  'kunming-longjin-pharma', 'beijing-ctrowell-technology-corp', 'bohai-leasing-a',
                  'xingyuan-environment-tech', 'datang-power', 's-goldleaf-jewel-a', 'tcl-corp-a', 'sanlux-rubber-a',
                  'jiangsu-exp', 'tongling-jingd', 'hengyi-petrochem-a', 'anhui-shengyun-environment-protect',
                  'hanhe-cable-a', 'aodong-a', 'xingrong-invest-a', 'hangxin-aviation-technology',
                  'bank-of-shanghai-co-ltd', 'baosheng', 'zhengping-road-bridge-construction', 'yunhai-metals-a',
                  'splendor-sci-tec-a', 'huayi-elec', 'xinmin-textile-a', 'beijing-sanju-environmental', 'aerosun-corp',
                  'jinling-mining-a', 'comfort-sci-tech-a', 'sh-belling', 'haitong-sec-ss', 'delisi-food-a',
                  'ningbo-bird', 'north-navigati', 'zhejiang-dehong-automotive-electric', 'huachang-chem-a',
                  'green-hitech-a', 'beingmate-a', 'hakim-unique-internet', 'surfilter-network-tech',
                  'feitian-technologies-co-ltd', 'tianan-coal', 'fudan-forward', 'changshan-a', 'china-shipping',
                  'urban-const', 'yongda-group-a', 'baoding-heavy-industry-co-ltd', 'jiangsu-guotai-a',
                  'rongxin-power-electronic-co-ltd', 'wonders-information', 'guangdong-eastone-century', 'fangda',
                  'em-technology', 'avit', 'xian-kaiyuan-a', 'jiangsu-pacific-quartz-co-ltd', 'ningbo-port',
                  'chixia-develop', 'jianghuai-auto', 'donghua', 'changlin', 'shanghai-sunglow-packaging',
                  'dongfeng-print', 'hs-laobaigan', 'zhujiang-brewery-a', 'jiangsu-broadcasting-cable-informat',
                  'luxin-packing-a', 'dazhong-trans', 'swan-fiber-co-ltd', 'tianbao-foods-a', 'xianju-pharm-a',
                  'dongguang-micro-a', 'beijing-baofeng-technology', 'weichai-power-a', 'capital-dev',
                  'hunan-jiudian-pharma', 'wanda-cinema-line-corp', 'tangel-publishing', 'tongyu-heavy-industry',
                  'pku-healthcare-a', 'shanghai-xuerong-bio-tech', 'hainan-haide-a', 'risen-energy', 'xcmg-machinery-a',
                  'dfd-chemical-a', 'changshu-tianyin-electromechan', 'foxconn', 'yutong-bus', 'yuneng-holding-a',
                  'wolong', 'changjiang-sec-a', 'longping-tech-a', 'shenzhen-jiawei-lighting', 'sansteel-mg-a',
                  'dongxing-securities', 'beijing-new-oriental-star-petro-eng', 'dalian-rubber', 'anhui-ankai-a',
                  's-tianjin-mari']
SHARE_LIST_PART = ['mesnac-a', 'kingsignal-tech', 'guangdong-tonze-electric', 'jiangsu-dagang-a', 'jinling-mining-a',
                   'sealand-securiti-a', 'shanghai-kinlita-chemical-co', 'lutianhua-a', 'central-empor',
                   'shenzhen-fenda-technology-a', 'china-merchants-shekou-industrial', 'zheshang-securities',
                   'minsheng-invest-a', 'global-infotech-co-ltd', 'tapai-group-a', 'chongqing-construction-engineering',
                   'chengdu-huaqi-houpu-holding-co-ltd', 'dingli-communications-corp-ltd',
                   'yantai-dongcheng-pharmaceutical-co', 'zhejiang-satellite-petrochem-a', 'zhongyuan-exp',
                   'maanshan-iron-ss', 'zhejiang-longsheng-auto-parts-co-lt', 'shen-huo-a', 'zhongsheng-pharm-a',
                   'wanwei-hi-tech', 'lingyun-ind', 'jian-feng-chem-a', 'anhui-water', 'sz-huaqiang-a',
                   'shenzhen-gongjin-electronics', 'longshine-tech', 'merchant-express-a', 'shenqi-phar',
                   'canudilo-fashion-a', 'great-wall-com-a', 'huaying-agri-a', 'fj-nanping-sun-a', 'soochow-securi',
                   'sichuan-gaojin-a', 'xin-jiang-hops', 'hubei-dinglong-chemical', 'akcome-solar-a', 'china-molybden',
                   'ningxia-buildi', 'aoto-electronics-a', 'ningbo-orient-wires-and-cables', 'susino-umbrella-a',
                   'cn-xd-electric', 'v-v-food---bev', 'yq-sea-cucumber-a', 'wuxi-hodgen-tech',
                   'suzhou-keda-technology-co-ltd', 'shenzhen-refond-optoelectronics',
                   'hunan-baili-engineering-sci---tech', 'hand-enterprise-solutions-co', 'tianyuan-tech-a',
                   'yunnei-power-a', 'konka-a', 'xiamen-c-d', 'tongwei', 'tj-tianbao-a', 'green-hitech-a',
                   'science-city-a', 'huaan-securities-co-ltd', 'northeast-sec-a', 'anxin-trust', 'guangtai-equip-a',
                   'xibei-bearing-a', 'billions-chemicl-a', 'andon-health-a', 'universal-scie', 'bj-hualian',
                   'guanlu-a', 'cecep-w-p', 'raisecom-technology-co-ltd', 'sl-pharm-a', 'broad-ocean-a',
                   'crystal-optech-a', 'dalian-zeus-entertainment', 'bank-of-nanjin', 'dalian-huarui-heavy-industry-a',
                   'chang-jiang-shipping-phoenix', 'cnlight-a', 'junzheng-ene-c', 'alpha-animation-a', 'yingliu-electr',
                   'western-metal-a', 'pku-healthcare-a', 'shanghai-pharm', 'xiwang-foodstuff-a', 'western-resour',
                   'xinri-hengli', 'guangdong-eastone-century', 'jiangxi-huawu-brake', 'suzhou-goldengreen-tech',
                   'dongbao-pharm', 'jiangsu-dewei-materials', 'gosuncn-a', 'guide-infrared-a']

if __name__ == "__main__":
    print(list(set(SHARE_LIST_RAW))[0:100])
